language: node_js

node_js:
  - stable

cache:
  directories:
    - "node_modules"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - npm i
  - npm run migrate

env:
  global:
    - CODECLIMATE_REPO_TOKEN=48edad6202b3538cddec1d4e232fd22fae42fbccbe792152e1b766c22b9e4339
    - DATABASE_TEST=postgresql://postgres@localhost/test_db
    - SECRET_KEY=supersecret

script:
  - npm run test

after_success: npm run coverage
